FROM gradle:jdk21-alpine
ARG PRODUCTION_STAGING
ARG JDBC_DATABASE_PASSWORD_STAGING
ARG JDBC_DATABASE_URL_STAGING
ARG JDBC_DATABASE_USERNAME_STAGING

ENV PRODUCTION ${PRODUCTION_STAGING}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD_STAGING}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL_STAGING}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME_STAGING}

WORKDIR /app
COPY ./build/libs/produk-transaksi-service-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java","-jar","produk-transaksi-service-0.0.1-SNAPSHOT.jar"]