global:
  scrape_interval: 15s # How frequently to scrape targets by default.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['34.143.169.251']